Universe = vanilla
Executable = main_batch.sh
accounting_group = aei.prod.cbc.bns

Error = /work/siqi.ni/error/gentbank/gentempbank_$(Process).err
Output = /work/siqi.ni/out/gentbank/gentempbank_$(Process).out 
Log = /work/siqi.ni/logs/gentbank/gentempbank_$(Process).log

should_transfer_files = YES 
transfer_input_files = GenTempBank.py, env.tar.gz 
WhenToTransferOutput = ON_EXIT 

Arguments = $(Process)
RequestCpus = 4
RequestMemory = 4000
Queue 100